### 获取用户余额信息
GET http://localhost:9001/imooc/ecommerce-service-account/balance/current-balance
Accept: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOnsiaWQiOjExLCJ1c2VybmFtZSI6Imtpc3N5In0sImp0aSI6IjE5MzVjODMwLWZlZjYtNDM1Yy1iZjAyLWQ2NjQwZDQ3NTU2ZCIsImV4cCI6MTY1MDU1NjgwMH0.APzt9VOpXVSBNkIBY81vOZOdARPQtgXhL-XdUUkzU_rv7mvZnmILPUogBK9jfH7XuwRAWOi04r1HwwKUF7gdbSbNhEpbQg3Vx_4VILbsDutuwl39pc_myw0pmvcfas9G-YF71dM3Iy6RClI6tqTQyi5WmDv01H8b-Bw2g2940iCkykwumHPtvoK-aP1HWEOt97zpsKwM5wqJaTxpwtLGROd3DDMkl1r9NcshMOSaXD3k1_-NHfEEtRPaArpMoBHcKffTFzZYi8dDmShYWqSZMIqZWwG1TDi1ZRiwUPrtZF53gZ_gtOmikexYmWcwNJqTP95_54NE74fukO5-ZSCsDQ

### 扣减用户余额信息
PUT http://localhost:9001/imooc/ecommerce-service-account/balance/deduct-balance
Content-Type: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOnsiaWQiOjExLCJ1c2VybmFtZSI6Imtpc3N5In0sImp0aSI6IjE5MzVjODMwLWZlZjYtNDM1Yy1iZjAyLWQ2NjQwZDQ3NTU2ZCIsImV4cCI6MTY1MDU1NjgwMH0.APzt9VOpXVSBNkIBY81vOZOdARPQtgXhL-XdUUkzU_rv7mvZnmILPUogBK9jfH7XuwRAWOi04r1HwwKUF7gdbSbNhEpbQg3Vx_4VILbsDutuwl39pc_myw0pmvcfas9G-YF71dM3Iy6RClI6tqTQyi5WmDv01H8b-Bw2g2940iCkykwumHPtvoK-aP1HWEOt97zpsKwM5wqJaTxpwtLGROd3DDMkl1r9NcshMOSaXD3k1_-NHfEEtRPaArpMoBHcKffTFzZYi8dDmShYWqSZMIqZWwG1TDi1ZRiwUPrtZF53gZ_gtOmikexYmWcwNJqTP95_54NE74fukO5-ZSCsDQ

{
  "userId": 10,
  "balance": 500
}