### 查询服务
GET http://localhost:9001/imooc/ecommerce-nacos-client/nacos-client/service-instance?serviceId=e-commerce-gateway
Accept: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOnsiaWQiOjExLCJ1c2VybmFtZSI6Imtpc3N5In0sImp0aSI6IjE1OTNlYWJhLTNhYjMtNDE3MC1hYjU4LTNlYTI4ZTczYWQwNyIsImV4cCI6MTY1MDI5NzYwMH0.Re8eDO0F85AIgtfzetu3M5udmUnXziwhM9464JD1ULoMtmyQYgsVz9U0YoEzsjO0ZeOqb9u9f42Fdkq9u_tMxm2GJxxHq-Xn9bqC70CHdaqBXkqlQ2Cz8b_B6xmZP4tkHLjxz1WqXE9eNQHFn2TPyf0I0IzJ_aPKB8GoOuWvR8eIiYLjSl5PCmE8QzGbEeU2C1tvRS-kFvi8SjdOX7M-ptFaifVeLYkcaCo4p1b6R9XjQ_c8IuRoQqLHD83AFvV8LJRCbPh7c5mTOkn-it3tLzpWzylGlIYDrs2Y32W_aXiV4Ivz8NQCIAcECtJ7CgGJcmqmLgC72M7HgV4mFt3mQw
token: imooc

### 查看 Sleuth 跟踪信息
GET http://localhost:9001/imooc/ecommerce-nacos-client/sleuth/trace-info
Accept: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOnsiaWQiOjExLCJ1c2VybmFtZSI6Imtpc3N5In0sImp0aSI6IjE1OTNlYWJhLTNhYjMtNDE3MC1hYjU4LTNlYTI4ZTczYWQwNyIsImV4cCI6MTY1MDI5NzYwMH0.Re8eDO0F85AIgtfzetu3M5udmUnXziwhM9464JD1ULoMtmyQYgsVz9U0YoEzsjO0ZeOqb9u9f42Fdkq9u_tMxm2GJxxHq-Xn9bqC70CHdaqBXkqlQ2Cz8b_B6xmZP4tkHLjxz1WqXE9eNQHFn2TPyf0I0IzJ_aPKB8GoOuWvR8eIiYLjSl5PCmE8QzGbEeU2C1tvRS-kFvi8SjdOX7M-ptFaifVeLYkcaCo4p1b6R9XjQ_c8IuRoQqLHD83AFvV8LJRCbPh7c5mTOkn-it3tLzpWzylGlIYDrs2Y32W_aXiV4Ivz8NQCIAcECtJ7CgGJcmqmLgC72M7HgV4mFt3mQw
token: imooc