### 查询服务
GET http://localhost:9001/imooc/ecommerce-nacos-client/nacos-client/service-instance?serviceId=e-commerce-gateway
Accept: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOnsiaWQiOjEzLCJ1c2VybmFtZSI6IjEyMzQ1NiJ9LCJqdGkiOiJmYTlkYzY3NC1kZDU5LTRhZjQtODlmYS04ZmMwNWNlNmJlNDIiLCJleHAiOjE2NDk5NTIwMDB9.WXtkm0rTWTeqS6MIiJO95V8NiFsPaStf7RYkN3_t-M9_3IsnU8l8vOTJiGgQ9xU-5tWLbiaGsDSLut8Ga2x-_YB7SmBOjWxsE_1QqLxWLHQHGU7Ulg40bs_ZkeX3PQ1bIeVPpG-F2xJx_hFJRC3KFFgoOxn-g-mX72zVTl6cc5LZkKGJ5Y5iEr7Hnt56Mx591AgWWqCTsZjO6DI7oPc6xdzC-6l_Woi5xrmypGVutea-Sx81OsICFfq8OoYOvMdafYb_H5LGnJDjJojQH1zhcx0AoEDetVjZC0mBwQ7u7remxK_t0ywBqOKr5N2Z1WNrX5Xe2Q8U4wj0V2x-bP14Fg
token: imooc
